/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IAaveLendingPoolCore } from "../IAaveLendingPoolCore";

export class IAaveLendingPoolCore__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveLendingPoolCore {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAaveLendingPoolCore;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_reserveUnderlyingToken",
        type: "address",
      },
    ],
    name: "getReserveATokenAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_reserveUnderlyingToken",
        type: "address",
      },
    ],
    name: "getReserveNormalizedIncome",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
