/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { TestUsdtTransferFrom } from "../TestUsdtTransferFrom";

export class TestUsdtTransferFrom__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<TestUsdtTransferFrom> {
    return super.deploy(overrides || {}) as Promise<TestUsdtTransferFrom>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TestUsdtTransferFrom {
    return super.attach(address) as TestUsdtTransferFrom;
  }
  connect(signer: Signer): TestUsdtTransferFrom__factory {
    return super.connect(signer) as TestUsdtTransferFrom__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TestUsdtTransferFrom {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as TestUsdtTransferFrom;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "usdtAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "testTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610118806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80632e4ebd1914602d575b600080fd5b605660048036036040811015604157600080fd5b506001600160a01b0381351690602001356058565b005b604080516323b872dd60e01b81523360048201523060248201526044810183905290516001600160a01b038416916323b872dd9160648083019260209291908290030181600087803b15801560ac57600080fd5b505af115801560bf573d6000803e3d6000fd5b505050506040513d602081101560d457600080fd5b505160de57600080fd5b505056fea2646970667358221220e1d0f3ccfbff7eb4f336d2b82aae403d3cd1329d765ba7e63eae8c081b2e1c2264736f6c63430007040033";
