/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAaveLendingPoolCoreInterface extends ethers.utils.Interface {
  functions: {
    "getReserveATokenAddress(address)": FunctionFragment;
    "getReserveNormalizedIncome(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getReserveATokenAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedIncome",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReserveATokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedIncome",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAaveLendingPoolCore extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAaveLendingPoolCoreInterface;

  functions: {
    getReserveATokenAddress(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getReserveATokenAddress(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getReserveNormalizedIncome(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getReserveNormalizedIncome(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getReserveATokenAddress(
    _reserveUnderlyingToken: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getReserveATokenAddress(address)"(
    _reserveUnderlyingToken: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getReserveNormalizedIncome(
    _reserveUnderlyingToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getReserveNormalizedIncome(address)"(
    _reserveUnderlyingToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getReserveATokenAddress(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getReserveATokenAddress(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getReserveNormalizedIncome(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReserveNormalizedIncome(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getReserveATokenAddress(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReserveATokenAddress(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReserveNormalizedIncome(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReserveNormalizedIncome(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReserveATokenAddress(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReserveATokenAddress(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReserveNormalizedIncome(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReserveNormalizedIncome(address)"(
      _reserveUnderlyingToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
