name: Run tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: module cache
        uses: actions/cache@v2
        with:
          path: |
            ~/node_modules
            ~/build
          key: ${{ runner.os }}-modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          check-latest: true
      - run: yarn
      - run: yarn compile && yarn hardhat coverage --testfiles \"test/core/*.spec.*\"
        env:
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
          NODE_OPTIONS: --max-old-space-size=7000
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/
      - run: bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -t f5bbafe2-26c0-4d31-bb29-8f6ca224eb88
